blueprint:
  name: Light Timer
  description: Turn off light after a number of seconds.
  domain: automation
  input:
    light:
      name: Light
      description: The light to monitor.
      selector:
        entity:
          domain: light
    duration:
      name: Duration
      description: Time in seconds before the light turns off automatically.
      default: 300
      selector:
        number:
          min: 1
          max: 86400
          unit_of_measurement: seconds
          mode: box

triggers:
  - trigger: state
    entity_id: !input light

conditions: []

actions:
  - action: pyscript.light_timer
    metadata: {}
    data:
      entity_id: !input light
      new_state: "{{ trigger.to_state.state }}"
      duration: !input duration

mode: single
